# Build stage

From node:22-alpine as build
Workdir /app
Copy . .
Run npm install
Run npm run build

# Run stage
From nginx-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "deamon off;"]