# Build stage

FROM node:22-alpine as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Run stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "deamon off;"]