# Build stage
FROM node:22-alpine AS build
WORKDIR /app

# Copy package.json trước để cache npm install
COPY package*.json ./
RUN npm install

# Copy code vào
COPY . .

# Build production
RUN npm run build

# Run stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/
# Expose cổng 80
EXPOSE 80

# Chạy nginx ở foreground (không detach)
CMD ["nginx", "-g", "daemon off;"]
